### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by memotiur** [pj8912/php-bard-api#1]
When I attempted to input the query "Canadian university scholarships for international students 2023," I encountered an error.

**Warning: Undefined array key 3" error in Bard.php on line 86** 
![Screenshot_2](https://github.com/pj8912/php-bard-api/assets/9117362/01c104d9-ec1f-42bd-abe3-3cb169925c15)

**Comment by pj8912** [comment]
works fine for me, try increasing timeout.
